BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_miles
            multiline: False
            text: ''
            on_text: app.handle_conversion(input_miles.text)
        BoxLayout:
            orientation: 'vertical'
            size_hint_x: 0.25
            Button:
                text: 'Up'
                on_press: app.handle_increment(input_miles.text, 1)
            Button:
                text: 'Down'
                on_press: app.handle_increment(input_miles.text, -1)
#    Button:
#        text: 'Convert miles to km'
#        on_press: app.handle_conversion(input_miles.text)
    Label:
        id: km_calculated
        text: app.km_result
        color: (1, 1, 0, 1)

